/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import handlers.Controller;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Type;
import model.User;

/**
 *
 * @author Mikkel
 */
public class TypeAndStatusHandlingPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserHandlingPanel
     */
    private ArrayList<Type> typeList;

    public TypeAndStatusHandlingPanel() throws SQLException, IOException {
        initComponents();
        typeList = Controller.typeList;
        Controller.fillTableWithType(tableType);
        Controller.fillTableWithStatus(tableStatus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldTypeName = new javax.swing.JTextField();
        textFieldDescription = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textFieldTypeName2 = new javax.swing.JTextField();
        textFieldDescription2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        buttonCreateType = new javax.swing.JButton();
        buttonDeleteType = new javax.swing.JButton();
        buttonUpdateType = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableType = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonUpdateStatus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableStatus = new javax.swing.JTable();
        buttonCreateStatus = new javax.swing.JButton();
        buttonDeleteStatus = new javax.swing.JButton();
        textFieldStatusNameCreate = new javax.swing.JTextField();
        textFieldStatusDescriptionCreate = new javax.swing.JTextField();
        textFieldStatusDescriptionChange = new javax.swing.JTextField();
        textFieldStatusNameChange = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel1.setText("Navn");

        jLabel3.setText("Beskrivelse");

        jLabel6.setText("Opret type");

        jLabel7.setText("Fjern type");

        jLabel8.setText("Rediger type");

        jLabel11.setText("Beskrivelse");

        jLabel12.setText("Navn");

        buttonCreateType.setText("Opret");
        buttonCreateType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateTypeActionPerformed(evt);
            }
        });

        buttonDeleteType.setText("Fjern");
        buttonDeleteType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteTypeActionPerformed(evt);
            }
        });

        buttonUpdateType.setText("Rediger");
        buttonUpdateType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateTypeActionPerformed(evt);
            }
        });

        tableType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Navn", "Beskrivelse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTypeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableType);

        jLabel9.setText("Opret type");

        jLabel4.setText("Beskrivelse");

        jLabel13.setText("Navn");

        jLabel2.setText("Navn");

        buttonUpdateStatus.setText("Rediger");
        buttonUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateStatusActionPerformed(evt);
            }
        });

        tableStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Navn", "Beskrivelse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStatusMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableStatus);

        buttonCreateStatus.setText("Opret");
        buttonCreateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateStatusActionPerformed(evt);
            }
        });

        buttonDeleteStatus.setText("Fjern");
        buttonDeleteStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteStatusActionPerformed(evt);
            }
        });

        jLabel10.setText("Rediger type");

        jLabel14.setText("Beskrivelse");

        jLabel15.setText("Fjern type");

        jLabel5.setText("Status håndtering");

        jLabel16.setText("Type håndtering");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textFieldStatusNameCreate)
                                            .addComponent(textFieldStatusDescriptionCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonDeleteStatus))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textFieldStatusNameChange)
                                            .addComponent(textFieldStatusDescriptionChange, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textFieldTypeName)
                                            .addComponent(textFieldDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonDeleteType))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textFieldTypeName2)
                                            .addComponent(textFieldDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonCreateStatus)
                                        .addGap(367, 367, 367)
                                        .addComponent(buttonUpdateStatus))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonCreateType)
                                        .addGap(367, 367, 367)
                                        .addComponent(buttonUpdateType)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(buttonCreateType))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(46, 46, 46)
                        .addComponent(buttonDeleteType))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldTypeName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(buttonUpdateType)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldStatusNameCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldStatusDescriptionCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(buttonCreateStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(46, 46, 46)
                        .addComponent(buttonDeleteStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldStatusNameChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldStatusDescriptionChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addComponent(buttonUpdateStatus)))
                .addGap(95, 95, 95))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreateTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateTypeActionPerformed
        try {
            Controller.dbHandler.createType(textFieldTypeName.getText(), textFieldDescription.getText());
            Controller.fillTableWithType(tableType);
        } catch (SQLException ex) {
            Logger.getLogger(TypeAndStatusHandlingPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TypeAndStatusHandlingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCreateTypeActionPerformed

    private void buttonUpdateTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateTypeActionPerformed
        DefaultTableModel modelTable = (DefaultTableModel) tableType.getModel();
        try {
            Controller.dbHandler.updateType(Integer.parseInt(modelTable.getValueAt(tableType.getSelectedRow(), 0).toString()),
                    textFieldTypeName.getText(),
                    textFieldDescription.getText());
            Controller.fillTableWithUser(tableType);
        } catch (SQLException ex) {
            Logger.getLogger(TypeAndStatusHandlingPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TypeAndStatusHandlingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonUpdateTypeActionPerformed

    private void tableTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTypeMouseClicked
        DefaultTableModel modelTable = (DefaultTableModel) tableType.getModel();
        textFieldTypeName2.setText(modelTable.getValueAt(tableType.getSelectedRow(), 1).toString());
        textFieldDescription2.setText(modelTable.getValueAt(tableType.getSelectedRow(), 2).toString());

    }//GEN-LAST:event_tableTypeMouseClicked

    private void buttonDeleteTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteTypeActionPerformed
        DefaultTableModel modelTable = (DefaultTableModel) tableType.getModel();

        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Sikker på du vil fjerne " + modelTable.getValueAt(tableType.getSelectedRow(), 1).toString(), "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Controller.dbHandler.deleteType(Integer.parseInt(modelTable.getValueAt(tableType.getSelectedRow(), 0).toString()));
                Controller.fillTableWithType(tableType);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TypeAndStatusHandlingPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TypeAndStatusHandlingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonDeleteTypeActionPerformed

    private void buttonUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateStatusActionPerformed
         DefaultTableModel modelTable = (DefaultTableModel) tableStatus.getModel();
        try {
            Controller.dbHandler.updateStatus(Integer.parseInt(modelTable.getValueAt(tableStatus.getSelectedRow(), 0).toString()),
                    textFieldStatusNameChange.getText(),
                    textFieldStatusDescriptionChange.getText());
            Controller.fillTableWithUser(tableStatus);
        } catch (SQLException ex) {
            Logger.getLogger(TypeAndStatusHandlingPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TypeAndStatusHandlingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonUpdateStatusActionPerformed

    private void tableStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStatusMouseClicked
        DefaultTableModel modelTable = (DefaultTableModel) tableStatus.getModel();
        textFieldStatusNameChange.setText(modelTable.getValueAt(tableStatus.getSelectedRow(), 1).toString());
        textFieldStatusDescriptionChange.setText(modelTable.getValueAt(tableStatus.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tableStatusMouseClicked

    private void buttonCreateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateStatusActionPerformed
        try {
            Controller.dbHandler.createStatus(textFieldStatusNameCreate.getText(), textFieldStatusDescriptionCreate.getText());
            Controller.fillTableWithType(tableStatus);
        } catch (SQLException ex) {
            Logger.getLogger(TypeAndStatusHandlingPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TypeAndStatusHandlingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_buttonCreateStatusActionPerformed

    private void buttonDeleteStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteStatusActionPerformed
         DefaultTableModel modelTable = (DefaultTableModel) tableType.getModel();

        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Sikker på du vil fjerne " + modelTable.getValueAt(tableStatus.getSelectedRow(), 1).toString(), "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Controller.dbHandler.deleteStatus(Integer.parseInt(modelTable.getValueAt(tableStatus.getSelectedRow(), 0).toString()));
                Controller.fillTableWithType(tableStatus);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TypeAndStatusHandlingPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TypeAndStatusHandlingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonDeleteStatusActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateStatus;
    private javax.swing.JButton buttonCreateType;
    private javax.swing.JButton buttonDeleteStatus;
    private javax.swing.JButton buttonDeleteType;
    private javax.swing.JButton buttonUpdateStatus;
    private javax.swing.JButton buttonUpdateType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableStatus;
    private javax.swing.JTable tableType;
    private javax.swing.JTextField textFieldDescription;
    private javax.swing.JTextField textFieldDescription2;
    private javax.swing.JTextField textFieldStatusDescriptionChange;
    private javax.swing.JTextField textFieldStatusDescriptionCreate;
    private javax.swing.JTextField textFieldStatusNameChange;
    private javax.swing.JTextField textFieldStatusNameCreate;
    private javax.swing.JTextField textFieldTypeName;
    private javax.swing.JTextField textFieldTypeName2;
    // End of variables declaration//GEN-END:variables
}
